# Generated by Django 4.2.23 on 2025-07-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
