# Generated by Django 4.2.23 on 2025-09-10 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
